.TH "propA" "1" "0.1.0" "Ulrike Mueckstein" "local"
.SH "NAME"
probA \- calculates the partiton function of a pairwise global alignment.  The partition function is then used to compute the probability of every possible match (or mismatch) between the two sequences. The partition function is also employed for stochastic backtracking which generates a correctly weighted ensemble of optimal and suboptimal alignments. 

.SH "SYNTAX"
\fBprobA\fR [\fI\fB\-\-help\fR\fP][\fI\fB\-\-version\fR\fP][\fI\fB\-T \fRvalue\fP][\fI\fB\-N \fRnumber\fP][\fI\fB\-\-endgaps \fR value\fP][\fI\fB\-\-noEG\fR\fP][\fI\fB\-\-DNA\fR\fP][\fI\fB\-\-prot\fR\fP][\fI\fB\-\-score_matrix \fRname\fP][\fI\fB\-\-noPS\fR\fP] 

.SH "DESCRIPTION"
\fBpropA\fR uses a dynamic programming algorithm to calculate the partition function over all possible alignments between two sequences. The results of the partion function are applied to determine the match probability for each possible match between any two sequence positions. To obtain the probability of each match i,j the partition function over all alignments, which contain this match, is divided by the partition function over all possible alignments of the two sequences.
.br 
The match probabilities are represented as a dot plot. The dot plot summarizes the information about the global esemble of all possilbe alignments.
.br 
Furthermore the partion function is used for stochastic back tracking generating a properly weighted ensemble of optimal and suboptimal alignments.   

.SH "OPTIONS"
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.TP 
\fB\-T\fR
T governs the relative weight of alignment paths with different scores. The lower the values of T the higher is the weight given to paths with high scores. The default value of T is 1. 
.TP 
\fB\-N\fR
N determines the number of alignments generated by the stochastic backtracking. The default value for N is one.
.TP 
\fB\-\-endgaps\fR
Terminal gaps get a score different from gaps inside the alignment. By default the score for terminal gaps is 0.
To change the score for terminal gaps set \-endgaps to the 
selected value.
.TP 
\fB\-\-noEg\fR
Terminal gaps are scored similar to gaps inside the alignment.
.TP 
\fB\-\-DNA\fR
Tells \fBprobA\fR to treat the input polymer as nucleic acids.
.TP 
\fB\-\-prot\fR
Tells \fBprobA\fR to treat the input polymer as proteins.
.TP 
\fB\-\-score_matrix\fR
determines the substitution matrix series used for protein alignments. probA provides three scoring matrix series:
.br 
gonnet\-series: To select the gonnet\-series use the abbrevation "gon".
.br 
blosum\-series: To select the blosum\-series use the abbrevation "blo".
.br 
pam\-series: To select the pam\-series use the abbrevation "pam".
.br 
The default scoring matrix series is the gonnet\-series.
.TP 
\fB\-\-pam\fR 
This option allows you to specify one scoring matrix out of the selected scoring matrix series. To select one matrix out of a matrix series give the pam\-distance for which this matrix is defined (for the pam and the gonnet matrix series) or the identity value (for the blosum series) as the argument. 
.br 
The default value for \-pam is \-1. If \-pam is set to \-1 probA makes an initial aligment of the two sequences to determine the pam\-distance and selects the appropriate scoring matrix.
.br 
Matrices provided by probA:
.br 
gonnet_series [gon]: gonnet_40, gonnet_80, gonnet_120, gonnet_160, gonnet_250, gonnet_300, gonnet_350;
.br  
blosum_series [blo]: blosum_30, blosum_50, blosum_62, blosum_80;
.br  
pam_series [pam]: pam_20, pam_60, pam_120, pam_350;
.TP 
\fB\-\-noPS\fR
To supresses the output of the match probability matrix as a dot plot use \-noPS. 
.TP 
.SH "AUTHORS"
Ulrike Mueckstein; 
ulim@tbi.univie.ac.at
